### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by wtennis** [learn-co-curriculum/phase-4-rails-practice-challenge-gym#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

> Add a link to the assignment in Canvas here.
https://learning.flatironschool.com/courses/4215/assignments/139513?module_item_id=289323

## What should be changed?
Typo. Suggested change in brackets:

"There are no tests for this application, so you'll need to check your progress by running the server and using Postman [to] make requests."

> Suggest your change here. Let us know what section or line of the Readme needs
> to be updated, and any proposed corrections. Include the line number(s) if
> possible.

## Additional context

> Add any other context about the problem here.

**Comment by lizbur10** [comment]
Hi @wtennis ! Thanks for bringing this to our attention - it has now been fixed. 

Thanks as always for contributing to the Flatiron School curriculum 💙
